# Bài 1
# name=input("Input your name :")
# print("Welcome"",",name,"!")
# Bài 2
# Firstname = input ("Enter your first name: ")
# Lastname = input ("Enter your last name: ")
# Phonenumber = input("Enter your phone number: ")
# print("Your registered name is : ", Firstname, Lastname,".")
# print("Your Phone number is : ", Phonenumber , ".")
# Bài 3 
# print("Name\t :\tMichael")
# print("Birthday\t :\t01/01/2001")
# Bài 4
# print("What year is it ?")
# year = int(input(" "))
# print("      \t              . : .")
# print("                    '.  :  .'")
# print("HAPPY NEW YEAR\t   .  '.:.'  .")
# print("!!! year !!!       .  .':'.  .")
# print("                    .'  :  '.")
# print("                      ' : '")
# Bai 5
from turtle import *
#forward(50)
#right(120)
#forward(100)
#right(120)
#forward(100)
#right(120)
#forward(50)
#right(90)
#mainloop()
#Bai 6 
#penup()
#forward(50)
#right(90)
#pendown()
#pensize(10)
#forward(150)
#right(90)
#forward(300)
#right(90)
#forward(300)
#right(90)
#forward(300)
#right(90)
#forward(150)
#penup()
#right(90)
#forward(25)
#pendown()
#pensize(0)
#right(90)
#forward(100)
#left(90)
#forward(225)
#left(90)
#forward(225)
#left(90)
#forward(225)
#left(90)
#forward(125)
#Bai 7
penup()
forward(200)
right(135)
pendown()
forward(200)
right(90)
forward(200)
right(90)
forward(200)
right(90)
forward(200)
penup()
right(-45)
backward(20)
pendown()
right(90)
forward(120)
right(90)
forward(240)
right(90)
forward(240)
right(90)
forward(240)
right(90)
forward(120)
penup()
right(90)
forward(120)
right(90)
mainloop()